### ISSUE TITLE
Missing NodeDeployment horizontal autoscaling fields

### ISSUE THREAD

**Issue by furkhat** [kubermatic/go-kubermatic#2]
Missing horizontal node autoscaling `MinReplicas` and `MaxReplicas` fields.
https://github.com/kubermatic/go-kubermatic/blob/master/models/node_deployment_spec.go#L18

**Comment by kdomanski** [comment]
Nothing is "missing" per se. We simply have no node autoscaling functionality. You're welcome to open a PR in the main kubermatic repo (the go-kubermatic code is autogenerated from the spec) if you have a proposal for autoscaler integration.
